### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/page-metadata-service#1]
While briefly testing this server (and realizing my cURL is pretty pathetic), it seems we may want to add a bit more error checking around validating the `urls` object before trying to call `.map()`.

### BAD CURL-ING!
```sh
$ curl -i -H "Content-Type: application/json" -X POST -d '{}' http://localhost:7001
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 1392
Date: Wed, 29 Jun 2016 20:59:07 GMT
Connection: keep-alive

TypeError: Cannot read property &#39;map&#39; of undefined<br> &nbsp; &nbsp;at /Users/pdehaan/dev/github/mozilla/page-metadata-service/service.js:55:33<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at Function.process_params (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/index.js:330:12)<br> &nbsp; &nbsp;at next (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/index.js:271:10)<br> &nbsp; &nbsp;at /Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/body-parser/lib/read.js:129:5<br> &nbsp; &nbsp;at invokeCallback (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/raw-body/index.js:262:16)
```

This caused my local server to :poop: itself with the following stack:

```
TypeError: Cannot read property 'map' of undefined
    at /Users/pdehaan/dev/github/mozilla/page-metadata-service/service.js:55:33
    at Layer.handle [as handle_request] (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/layer.js:95:5)
    at /Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/express/lib/router/index.js:271:10)
    at /Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/Users/pdehaan/dev/github/mozilla/page-metadata-service/node_modules/raw-body/index.js:262:16)
```

Code in question is (service.js:54-57):

```js
app.post('/', function(req, res) {
  const promises = req.body.urls.map((url) => {
    return getUrlMetadata(url);
  });
```

---

### GOOD CURL-ING

```sh
~ curl -i -H "Content-Type: application/json" -X POST -d '{"urls": ["https://bing.com"]}' http://localhost:7001
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 461
ETag: W/"1cd-hif3Pq3n/7Bk69jRvpoHiQ"
Date: Wed, 29 Jun 2016 20:44:10 GMT
Connection: keep-alive

{
  "error": "",
  "urls": {
    "https://bing.com": {
      "description": "Bing helps you turn information into action, making it faster and easier to go from searching to doing.",
      "icon_url": "https://www.bing.com/fd/s/a/hp/bing.svg",
      "image_url": "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAEALAAAAAABAAEAAAIBTAA7",
      "title": "Bing",
      "url": "https://bing.com",
      "original_url": "https://bing.com",
      "provider_url": "https://bing.com",
      "favicon_url": "https://bing.com/favicon.ico"
    }
  }
}
```

**Comment by pdehaan** [comment]
Unable to reproduce in latest master branch. Closing.

```sh
$ curl -XPOST -i -H "content-type: application/json" -d '{}' http://localhost:7001 | JSON

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 57
ETag: W/"39-DATCOl+kpDISCiW+0MhzZQ"
Date: Tue, 09 Aug 2016 18:52:45 GMT
Connection: keep-alive

{
  "error": "Unable to locate 'urls' in body: {}",
  "urls": []
}
```
