### ISSUE TITLE
Add more/some data validation on incoming `urls` argument

### ISSUE THREAD

**Issue by pdehaan** [mozilla/page-metadata-service#44]
My complete stupidity (and hacking on [httpie](https://github.com/jkbrzt/httpie)) seems to have broken something. I'm currently trying to figure out how to POST that `urls` array using HTTPie instead of cURL, but then this happened.

```
$ http POST https://metadata.dev.mozaws.net/v1/metadata urls='["https://bing.com"]' 'Content-

Type:application/json'
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 871
Content-Type: text/html; charset=utf-8
Date: Thu, 11 Aug 2016 00:51:51 GMT
Server: nginx/1.9.9
X-Content-Type-Options: nosniff
X-Powered-By: Express

TypeError: req.body.urls.map is not a function<br> &nbsp; &nbsp;at /app/service.js:100:34<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /app/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)<br> &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/index.js:271:10)<br> &nbsp; &nbsp;at /app/node_modules/body-parser/lib/read.js:129:5<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/raw-body/index.js:262:16)
```

> _"TypeError: req.body.urls.map is not a function<br> &nbsp; &nbsp;at [/app/service.js\:\100\:34](https://github.com/mozilla/page-metadata-service/blob/f24b63da1a0adebeb82e11937f336493d25dbea9/app/service.js#L100)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /app/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)<br> &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/index.js:271:10)<br> &nbsp; &nbsp;at /app/node_modules/body-parser/lib/read.js:129:5<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/raw-body/index.js:262:16)"_

Sketchy code in question is [./app/service.js:100](https://github.com/mozilla/page-metadata-service/blob/f24b63da1a0adebeb82e11937f336493d25dbea9/app/service.js#L100):

```js
const promises = req.body.urls.map((url) => getUrlMetadata(url));
```

We may need to add some more [`!Array.isArray(req.body.urls)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)-esque validation around L95-98:

```js
  if (!req.body.urls || req.body.urls.length <= 0) {
    fail(errorMessages.urlsRequired, 400);
    return;
  }
```

**Comment by pdehaan** [comment]
Dear Future @pdehaan,

Per `https://github.com/jkbrzt/httpie/issues/121`, this seems to work:

```sh
echo '{"urls": ["https://bing.com"]}' | http POST https://metadata.dev.mozaws.net/v1/metadata 'Content-Type:application/json'

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 436
Content-Type: application/json; charset=utf-8
Date: Thu, 11 Aug 2016 00:56:49 GMT
ETag: W/"1b4-DvvSqpJmsS3xmDhR9F8sNQ"
Server: nginx/1.9.9
Strict-Transport-Security: max-age=31536000
X-Powered-By: Express

{
    "error": "",
    "urls": {
        "https://bing.com": {
            "description": "Bing helps you turn information into action, making it faster and easier to go from searching to doing.",
            "favicon_url": "https://bing.com/fd/s/a/hp/bing.svg",
            "images": [
                {
                    "entropy": 1,
                    "height": 500,
                    "url": "data://undefinedimage/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAEALAAAAAABAAEAAAIBTAA7",
                    "width": 500
                }
            ],
            "original_url": "https://bing.com",
            "title": "Bing",
            "url": "https://bing.com"
        }
    }
}
```

Sincerely,
Past @pdehaan
