### ISSUE TITLE
Error when developing locally unless you generate version.json

### ISSUE THREAD

**Issue by pdehaan** [mozilla/page-metadata-service#65]
Found in 803831d27785f703f1573fcd7781c5b7be8443a9

Currently, running `$ npm start` in the app/ directory fails hard, with the following:

```sh
$ npm start

> page-metadata-service@0.1.0 start /Users/pdehaan/dev/github/mozilla/page-metadata-service/app
> node service

module.js:442
    throw err;
    ^

Error: Cannot find module './version.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pdehaan/dev/github/mozilla/page-metadata-service/app/service.js:6:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

We don't have an ./app/version.json checked in to the repo. It's magically created via [./scripts/build.sh](https://github.com/mozilla/page-metadata-service/blob/master/scripts/build.sh):

```sh
./scripts/echo_version_json.sh > ./app/version.json
docker build -t app:build app/
```

I don't have Docker running in this Terminal session, so that `docker build -t app:build app/` also fails locally for me.

Cheapest workaround is to run the `./scripts/echo_version_json.sh > ./app/version.json` command locally, or try shimming it into my ./app/package.json as a script hook:

```diff
diff --git a/app/package.json b/app/package.json
index 68bbfbb..4e9598f 100644
--- a/app/package.json
+++ b/app/package.json
@@ -47,6 +47,7 @@
     "start": "node service",
     "test": "npm-run-all test:*",
     "test:lint": "eslint .",
-    "test:mocha": "istanbul cover _mocha --report lcovonly -- test/*.js -R spec"
+    "test:mocha": "istanbul cover _mocha --report lcovonly -- test/*.js -R spec",
+    "prestart": "../scripts/echo_version_json.sh > version.json"
   }
 }
```

... which will recreate the ./version.json file every time you run `$ npm start`.

**Comment by pdehaan** [comment]
Slightly more hideous Node-centric solution, which uses `writeFileSync()` and `execFileSync()` to pipe the contents of the echo_version_json.sh into a version.json file:

```js
const {writeFileSync} = require('fs');
const {execFileSync} = require('child_process');

try {
  const versionJson = execFileSync('../scripts/echo_version_json.sh');
  writeFileSync('./version.json', versionJson);
} catch (err) {
  console.error(err);
  process.exit(1);
}
```
